Feature/topics
siddharth-vinsol/quora-clone pull request #5
Opened 2022-09-17 05:02 UTC by siddharth-vinsol

- Add multiple topics where user can answer on(comma separated auto suggest).
- Add topics when creating question
- User can browse questions by topics

2022-09-20 21:57 UTC, shubhamjuneja1 requested changes

2022-09-20 21:57 UTC, shubhamjuneja1 commented on app/views/homepage/index.html.erb
> +      <%= form.collection_check_boxes :topics_name_eq_any, Topic.order(:name), :name, :name do |b| %>
Topic.order(:name) method

2022-09-20 21:57 UTC, shubhamjuneja1 commented on app/javascript/scripts/topics_handler.js
> +let topicsHandler = new TopicsHandler($('.topics-list'));
use data attribute

2022-09-22 07:32 UTC, siddharth-vinsol commented on app/javascript/scripts/topics_handler.js
> +let topicsHandler = new TopicsHandler($('.topics-list'));
rename to Select2Handler

2022-09-25 21:13 UTC, shubhamjuneja1 approved these changes

2022-09-25 21:13 UTC, shubhamjuneja1 commented on Gemfile
> +gem 'select2-rails'
version?

2022-09-27 20:09 UTC, shubhamjuneja1 approved these changes

2022-10-07 04:41 UTC, merged